[package]
name = "phitoo"
version = "0.1.0"
edition = "2021"
description = "v2ray URL parser"
repository = "https://github.com/iyarivky/phitoo/"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"